import type { Metadata } from "next";
import { getServerSession } from "next-auth";

import Header from "@/components/Header";
import AuthProvider from "@/components/AuthProvider";

import 'bootstrap-icons/font/bootstrap-icons.css'
import "./global.css"

export const metadata: Metadata = {
  title: "RizzStore",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode;}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body>
        <AuthProvider session={session}>
          <Header />
          {children}
        </AuthProvider>
        {/* TODO: add footer */}
      </body>
    </html>
  );
}
